server:
  port: 9292
  servlet:
    context-path: /consumer/v1
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: Service.ALIBABA.OBB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/alibabauser?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: ndwmd1230
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,slf4j,wall


    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  client:
    config:
      default:
        logger-level: BASIC
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
