server:
  port: 9191
  servlet:
    context-path: /server/v1
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: Service.ALIBABA.TRB
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/alibabauser?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: ndwmd1230
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,slf4j,wall


    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: Ticket_
      cache-null-values: true
      use-key-prefix: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

